// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOlCW6boXCecvfWPL1M7Td3CSuZEozdk',
    appId: '1:606453005976:web:d7a05e7aaad96a9a13daed',
    messagingSenderId: '606453005976',
    projectId: 'budgetplanner-bbc0f',
    authDomain: 'budgetplanner-bbc0f.firebaseapp.com',
    storageBucket: 'budgetplanner-bbc0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw40q3zaBss4WPOOVGvAp2-Hdrmk73NQA',
    appId: '1:606453005976:android:eabcd5f6a6097f5f13daed',
    messagingSenderId: '606453005976',
    projectId: 'budgetplanner-bbc0f',
    storageBucket: 'budgetplanner-bbc0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlRHMMI6lN7AzGyeZnqBck1u7v56YHHXc',
    appId: '1:606453005976:ios:635d11bdae0e088013daed',
    messagingSenderId: '606453005976',
    projectId: 'budgetplanner-bbc0f',
    storageBucket: 'budgetplanner-bbc0f.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlRHMMI6lN7AzGyeZnqBck1u7v56YHHXc',
    appId: '1:606453005976:ios:8427f65b263ea3ce13daed',
    messagingSenderId: '606453005976',
    projectId: 'budgetplanner-bbc0f',
    storageBucket: 'budgetplanner-bbc0f.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
